### ISSUE TITLE
1.15 reflection warning

### ISSUE THREAD

**Issue by kbartek05** [TheBusyBiscuit/HotbarPets#17]
I'm running the plugin on Paper 1.15.
```java
[14:53:24 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.TileEntitySkull.getGameProfile()
[14:53:24 WARN]:        at java.lang.Class.getMethod(Class.java:1786)
[14:53:24 WARN]:        at me.mrCookieSlime.CSCoreLibPlugin.general.World.CustomSkull.<clinit>(CustomSkull.java:42)
[14:53:24 WARN]:        at io.github.thebusybiscuit.hotbarpets.groups.FarmAnimals.load(FarmAnimals.java:27)
[14:53:24 WARN]:        at io.github.thebusybiscuit.hotbarpets.groups.FarmAnimals.<init>(FarmAnimals.java:17)
[14:53:24 WARN]:        at io.github.thebusybiscuit.hotbarpets.HotbarPets.onEnable(HotbarPets.java:48)
[14:53:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[14:53:24 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[14:53:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[14:53:24 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468)
[14:53:24 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382)
[14:53:24 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481)
[14:53:24 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290)
[14:53:24 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[14:53:24 WARN]:        at java.lang.Thread.run(Thread.java:748)
```
Plugin is enabled, though.

**Comment by TheBusyBiscuit** [comment]
You did not install a CS-CoreLib build that is compatible with 1.15...
